  
language: php

php:
  - '7.3'

before_install:
  - sudo apt update
  - sudo apt install tesseract-ocr

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload

script:
  - vendor/bin/phpunit